name: 'Build'

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Set up Node.js env
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Upload the build files
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/
