name: Code-Integration workflow

on:
  pull_request:
    branch: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node env
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Installing the dependencies
        run: npm ci

      - name: Running tests
        run: npm test
